
language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

install:
  - python -m pip install pytest speedy-antlr-tool

script:
  - python setup.py install
  - pytest

stages:
  - test
  # Only execute deployment stage on tagged release commits in the form of "v1.2.3"
  # and from your repository (e.g. not PRs).
  - name: deploy
    if: repo = amykyta3/speedy-antlr-example AND tag =~ ^v\d+\.\d+\.\d+$

jobs:
  include:

    # Deploy source distribution
    - stage: deploy
      name: Deploy source distribution
      install: python -m pip install twine
      script: python setup.py sdist --formats=gztar
      after_success: python -m twine upload --skip-existing dist/*.tar.gz

    # Deploy on linux
    - stage: deploy
      name: Build and deploy Linux wheels
      services: docker
      install: python -m pip install twine cibuildwheel==1.1.0
      script: python -m cibuildwheel --output-dir wheelhouse
      after_success: python -m twine upload --skip-existing wheelhouse/*.whl

    # Deploy on mac
    - stage: deploy
      name: Build and deploy macOS wheels
      os: osx
      language: shell
      install: python -m pip install twine cibuildwheel==1.1.0
      script: python -m cibuildwheel --output-dir wheelhouse
      after_success: python -m twine upload --skip-existing wheelhouse/*.whl

    # Deploy on windows
    - stage: deploy
      name: Build and deploy Windows wheels
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.1
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
      install: python -m pip install twine cibuildwheel==1.1.0
      script: python -m cibuildwheel --output-dir wheelhouse
      after_success: python -m twine upload --skip-existing wheelhouse/*.whl

env:
  global:
    # Don't deploy python2.7 (not supported), or osx 10.6 (no C++11 support)
    - CIBW_SKIP="cp27-* *macosx_10_6*"

    # Note: TWINE_USERNAME and TWINE_PASSWORD is set in Travis settings
    # Recommend using PyPi API tokens. See https://pypi.org/help/#apitoken
    
    # Signal setup.py to fail if binary build fails
    - SPAM_EXAMPLE_REQUIRE_CI_BINARY_BUILD
