/*
 * This file was auto-generated by speedy-antlr-tool v1.4.3
 *  https://github.com/amykyta3/speedy-antlr-tool
 */

#pragma once

#include "NaturalParserBaseVisitor.h"
#include "speedy_antlr.h"

class SA_NaturalTranslator : public NaturalParserBaseVisitor {
    speedy_antlr::Translator *translator;

    // Cached context classes
    PyObject *ProgramContext_cls = NULL;
    PyObject *LineNumberStatementContext_cls = NULL;
    PyObject *StatementContext_cls = NULL;
    PyObject *LabelContext_cls = NULL;
    PyObject *DataDefinitionContext_cls = NULL;
    PyObject *CompressStatementContext_cls = NULL;
    PyObject *CompressEndContext_cls = NULL;
    PyObject *InputStatementContext_cls = NULL;
    PyObject *InputOptionsContext_cls = NULL;
    PyObject *InputUsingMapContext_cls = NULL;
    PyObject *VariableContext_cls = NULL;
    PyObject *ReinputStatementContext_cls = NULL;
    PyObject *ReinputOptionsContext_cls = NULL;
    PyObject *SortStatementContext_cls = NULL;
    PyObject *ExamineStatementContext_cls = NULL;
    PyObject *ExamineOptionsContext_cls = NULL;
    PyObject *MoveStatementContext_cls = NULL;
    PyObject *MoveOptionsContext_cls = NULL;
    PyObject *RepeatStatementContext_cls = NULL;
    PyObject *DoStatementContext_cls = NULL;
    PyObject *StoreStatementContext_cls = NULL;
    PyObject *StorePreview2Context_cls = NULL;
    PyObject *StoreConditionContext_cls = NULL;
    PyObject *FindStatementContext_cls = NULL;
    PyObject *FindQueryContext_cls = NULL;
    PyObject *FindNumberContext_cls = NULL;
    PyObject *FindPreview1Context_cls = NULL;
    PyObject *FindPreview2Context_cls = NULL;
    PyObject *ReadStatementContext_cls = NULL;
    PyObject *ReadQueryContext_cls = NULL;
    PyObject *ReadPreview1Context_cls = NULL;
    PyObject *ReadPreview2Context_cls = NULL;
    PyObject *UpdateStatementContext_cls = NULL;
    PyObject *UpdateStartlineContext_cls = NULL;
    PyObject *DeleteStatementContext_cls = NULL;
    PyObject *GetStatementsContext_cls = NULL;
    PyObject *GetTabledStatementsContext_cls = NULL;
    PyObject *GetTabledOptionsContext_cls = NULL;
    PyObject *GetTransactionStatementContext_cls = NULL;
    PyObject *GetSameStatementContext_cls = NULL;
    PyObject *HistogramStatementContext_cls = NULL;
    PyObject *HistogramQueryContext_cls = NULL;
    PyObject *HistogramPreviewContext_cls = NULL;
    PyObject *HistogramOptionsContext_cls = NULL;
    PyObject *EndTransactionContext_cls = NULL;
    PyObject *BackoutTransactionContext_cls = NULL;
    PyObject *ReadworkfileStatementContext_cls = NULL;
    PyObject *WorkfilenumberOptionContext_cls = NULL;
    PyObject *ReadworkfileOptionsContext_cls = NULL;
    PyObject *AtEndOfFileStatementContext_cls = NULL;
    PyObject *WriteworkfileStatementContext_cls = NULL;
    PyObject *CloseworkfileStatementContext_cls = NULL;
    PyObject *NoRecordsFoundStatementContext_cls = NULL;
    PyObject *AtStartOfDataStatementContext_cls = NULL;
    PyObject *FormatStatementContext_cls = NULL;
    PyObject *FormatOptionsContext_cls = NULL;
    PyObject *AssignmentStatementContext_cls = NULL;
    PyObject *IncludeStatementContext_cls = NULL;
    PyObject *RedefineStatementContext_cls = NULL;
    PyObject *RedefineBodyContext_cls = NULL;
    PyObject *ResetStatementContext_cls = NULL;
    PyObject *CallnatStatementContext_cls = NULL;
    PyObject *SetkeyStatementContext_cls = NULL;
    PyObject *PerformStatementContext_cls = NULL;
    PyObject *SubroutineNamesContext_cls = NULL;
    PyObject *FetchStatementContext_cls = NULL;
    PyObject *CallStatementContext_cls = NULL;
    PyObject *ForStatementContext_cls = NULL;
    PyObject *AcceptRejectIfStatementContext_cls = NULL;
    PyObject *DecisionStatementContext_cls = NULL;
    PyObject *IfStatementContext_cls = NULL;
    PyObject *IfStructuredStatementContext_cls = NULL;
    PyObject *ElseStructuredContext_cls = NULL;
    PyObject *IfElseStatementContext_cls = NULL;
    PyObject *IfMultilinedStatementContext_cls = NULL;
    PyObject *IfSinglelinedStatementContext_cls = NULL;
    PyObject *ElseMultilinedStatementContext_cls = NULL;
    PyObject *ElseSinglelinedStatementContext_cls = NULL;
    PyObject *OnelinerBodyContext_cls = NULL;
    PyObject *ConditionContext_cls = NULL;
    PyObject *OptionalConditionContext_cls = NULL;
    PyObject *OperandContext_cls = NULL;
    PyObject *NaturalKeywordsContext_cls = NULL;
    PyObject *LogicalOpContext_cls = NULL;
    PyObject *SubroutineContext_cls = NULL;
    PyObject *BlockContentSubroutineContext_cls = NULL;
    PyObject *SubroutineStatementContext_cls = NULL;
    PyObject *FunctionDefinitionContext_cls = NULL;
    PyObject *BlockContentContext_cls = NULL;
    PyObject *ValueAssignmentContext_cls = NULL;
    PyObject *AssignStatementContext_cls = NULL;
    PyObject *AddOperationContext_cls = NULL;
    PyObject *MultiplyOperationContext_cls = NULL;
    PyObject *SubtractOperationContext_cls = NULL;
    PyObject *DivideOperationContext_cls = NULL;
    PyObject *ComputeOperationContext_cls = NULL;
    PyObject *ArithmaticOperationContext_cls = NULL;
    PyObject *OptionalComputeContext_cls = NULL;
    PyObject *CalculationsContext_cls = NULL;
    PyObject *AddContentContext_cls = NULL;
    PyObject *CompOpContext_cls = NULL;
    PyObject *ArithmaticOpContext_cls = NULL;
    PyObject *EndStatementContext_cls = NULL;
    PyObject *OtherStatementContext_cls = NULL;

    public:
    SA_NaturalTranslator(speedy_antlr::Translator *translator);
    ~SA_NaturalTranslator();
    antlrcpp::Any visitProgram(NaturalParser::ProgramContext *ctx);

    antlrcpp::Any visitLineNumberStatement(NaturalParser::LineNumberStatementContext *ctx);

    antlrcpp::Any visitStatement(NaturalParser::StatementContext *ctx);

    antlrcpp::Any visitLabel(NaturalParser::LabelContext *ctx);

    antlrcpp::Any visitDataDefinition(NaturalParser::DataDefinitionContext *ctx);

    antlrcpp::Any visitCompressStatement(NaturalParser::CompressStatementContext *ctx);

    antlrcpp::Any visitCompressEnd(NaturalParser::CompressEndContext *ctx);

    antlrcpp::Any visitInputStatement(NaturalParser::InputStatementContext *ctx);

    antlrcpp::Any visitInputOptions(NaturalParser::InputOptionsContext *ctx);

    antlrcpp::Any visitInputUsingMap(NaturalParser::InputUsingMapContext *ctx);

    antlrcpp::Any visitVariable(NaturalParser::VariableContext *ctx);

    antlrcpp::Any visitReinputStatement(NaturalParser::ReinputStatementContext *ctx);

    antlrcpp::Any visitReinputOptions(NaturalParser::ReinputOptionsContext *ctx);

    antlrcpp::Any visitSortStatement(NaturalParser::SortStatementContext *ctx);

    antlrcpp::Any visitExamineStatement(NaturalParser::ExamineStatementContext *ctx);

    antlrcpp::Any visitExamineOptions(NaturalParser::ExamineOptionsContext *ctx);

    antlrcpp::Any visitMoveStatement(NaturalParser::MoveStatementContext *ctx);

    antlrcpp::Any visitMoveOptions(NaturalParser::MoveOptionsContext *ctx);

    antlrcpp::Any visitRepeatStatement(NaturalParser::RepeatStatementContext *ctx);

    antlrcpp::Any visitDoStatement(NaturalParser::DoStatementContext *ctx);

    antlrcpp::Any visitStoreStatement(NaturalParser::StoreStatementContext *ctx);

    antlrcpp::Any visitStorePreview2(NaturalParser::StorePreview2Context *ctx);

    antlrcpp::Any visitStoreCondition(NaturalParser::StoreConditionContext *ctx);

    antlrcpp::Any visitFindStatement(NaturalParser::FindStatementContext *ctx);

    antlrcpp::Any visitFindQuery(NaturalParser::FindQueryContext *ctx);

    antlrcpp::Any visitFindNumber(NaturalParser::FindNumberContext *ctx);

    antlrcpp::Any visitFindPreview1(NaturalParser::FindPreview1Context *ctx);

    antlrcpp::Any visitFindPreview2(NaturalParser::FindPreview2Context *ctx);

    antlrcpp::Any visitReadStatement(NaturalParser::ReadStatementContext *ctx);

    antlrcpp::Any visitReadQuery(NaturalParser::ReadQueryContext *ctx);

    antlrcpp::Any visitReadPreview1(NaturalParser::ReadPreview1Context *ctx);

    antlrcpp::Any visitReadPreview2(NaturalParser::ReadPreview2Context *ctx);

    antlrcpp::Any visitUpdateStatement(NaturalParser::UpdateStatementContext *ctx);

    antlrcpp::Any visitUpdateStartline(NaturalParser::UpdateStartlineContext *ctx);

    antlrcpp::Any visitDeleteStatement(NaturalParser::DeleteStatementContext *ctx);

    antlrcpp::Any visitGetStatements(NaturalParser::GetStatementsContext *ctx);

    antlrcpp::Any visitGetTabledStatements(NaturalParser::GetTabledStatementsContext *ctx);

    antlrcpp::Any visitGetTabledOptions(NaturalParser::GetTabledOptionsContext *ctx);

    antlrcpp::Any visitGetTransactionStatement(NaturalParser::GetTransactionStatementContext *ctx);

    antlrcpp::Any visitGetSameStatement(NaturalParser::GetSameStatementContext *ctx);

    antlrcpp::Any visitHistogramStatement(NaturalParser::HistogramStatementContext *ctx);

    antlrcpp::Any visitHistogramQuery(NaturalParser::HistogramQueryContext *ctx);

    antlrcpp::Any visitHistogramPreview(NaturalParser::HistogramPreviewContext *ctx);

    antlrcpp::Any visitHistogramOptions(NaturalParser::HistogramOptionsContext *ctx);

    antlrcpp::Any visitEndTransaction(NaturalParser::EndTransactionContext *ctx);

    antlrcpp::Any visitBackoutTransaction(NaturalParser::BackoutTransactionContext *ctx);

    antlrcpp::Any visitReadworkfileStatement(NaturalParser::ReadworkfileStatementContext *ctx);

    antlrcpp::Any visitWorkfilenumberOption(NaturalParser::WorkfilenumberOptionContext *ctx);

    antlrcpp::Any visitReadworkfileOptions(NaturalParser::ReadworkfileOptionsContext *ctx);

    antlrcpp::Any visitAtEndOfFileStatement(NaturalParser::AtEndOfFileStatementContext *ctx);

    antlrcpp::Any visitWriteworkfileStatement(NaturalParser::WriteworkfileStatementContext *ctx);

    antlrcpp::Any visitCloseworkfileStatement(NaturalParser::CloseworkfileStatementContext *ctx);

    antlrcpp::Any visitNoRecordsFoundStatement(NaturalParser::NoRecordsFoundStatementContext *ctx);

    antlrcpp::Any visitAtStartOfDataStatement(NaturalParser::AtStartOfDataStatementContext *ctx);

    antlrcpp::Any visitFormatStatement(NaturalParser::FormatStatementContext *ctx);

    antlrcpp::Any visitFormatOptions(NaturalParser::FormatOptionsContext *ctx);

    antlrcpp::Any visitAssignmentStatement(NaturalParser::AssignmentStatementContext *ctx);

    antlrcpp::Any visitIncludeStatement(NaturalParser::IncludeStatementContext *ctx);

    antlrcpp::Any visitRedefineStatement(NaturalParser::RedefineStatementContext *ctx);

    antlrcpp::Any visitRedefineBody(NaturalParser::RedefineBodyContext *ctx);

    antlrcpp::Any visitResetStatement(NaturalParser::ResetStatementContext *ctx);

    antlrcpp::Any visitCallnatStatement(NaturalParser::CallnatStatementContext *ctx);

    antlrcpp::Any visitSetkeyStatement(NaturalParser::SetkeyStatementContext *ctx);

    antlrcpp::Any visitPerformStatement(NaturalParser::PerformStatementContext *ctx);

    antlrcpp::Any visitSubroutineNames(NaturalParser::SubroutineNamesContext *ctx);

    antlrcpp::Any visitFetchStatement(NaturalParser::FetchStatementContext *ctx);

    antlrcpp::Any visitCallStatement(NaturalParser::CallStatementContext *ctx);

    antlrcpp::Any visitForStatement(NaturalParser::ForStatementContext *ctx);

    antlrcpp::Any visitAcceptRejectIfStatement(NaturalParser::AcceptRejectIfStatementContext *ctx);

    antlrcpp::Any visitDecisionStatement(NaturalParser::DecisionStatementContext *ctx);

    antlrcpp::Any visitIfStatement(NaturalParser::IfStatementContext *ctx);

    antlrcpp::Any visitIfStructuredStatement(NaturalParser::IfStructuredStatementContext *ctx);

    antlrcpp::Any visitElseStructured(NaturalParser::ElseStructuredContext *ctx);

    antlrcpp::Any visitIfElseStatement(NaturalParser::IfElseStatementContext *ctx);

    antlrcpp::Any visitIfMultilinedStatement(NaturalParser::IfMultilinedStatementContext *ctx);

    antlrcpp::Any visitIfSinglelinedStatement(NaturalParser::IfSinglelinedStatementContext *ctx);

    antlrcpp::Any visitElseMultilinedStatement(NaturalParser::ElseMultilinedStatementContext *ctx);

    antlrcpp::Any visitElseSinglelinedStatement(NaturalParser::ElseSinglelinedStatementContext *ctx);

    antlrcpp::Any visitOnelinerBody(NaturalParser::OnelinerBodyContext *ctx);

    antlrcpp::Any visitCondition(NaturalParser::ConditionContext *ctx);

    antlrcpp::Any visitOptionalCondition(NaturalParser::OptionalConditionContext *ctx);

    antlrcpp::Any visitOperand(NaturalParser::OperandContext *ctx);

    antlrcpp::Any visitNaturalKeywords(NaturalParser::NaturalKeywordsContext *ctx);

    antlrcpp::Any visitLogicalOp(NaturalParser::LogicalOpContext *ctx);

    antlrcpp::Any visitSubroutine(NaturalParser::SubroutineContext *ctx);

    antlrcpp::Any visitBlockContentSubroutine(NaturalParser::BlockContentSubroutineContext *ctx);

    antlrcpp::Any visitSubroutineStatement(NaturalParser::SubroutineStatementContext *ctx);

    antlrcpp::Any visitFunctionDefinition(NaturalParser::FunctionDefinitionContext *ctx);

    antlrcpp::Any visitBlockContent(NaturalParser::BlockContentContext *ctx);

    antlrcpp::Any visitValueAssignment(NaturalParser::ValueAssignmentContext *ctx);

    antlrcpp::Any visitAssignStatement(NaturalParser::AssignStatementContext *ctx);

    antlrcpp::Any visitAddOperation(NaturalParser::AddOperationContext *ctx);

    antlrcpp::Any visitMultiplyOperation(NaturalParser::MultiplyOperationContext *ctx);

    antlrcpp::Any visitSubtractOperation(NaturalParser::SubtractOperationContext *ctx);

    antlrcpp::Any visitDivideOperation(NaturalParser::DivideOperationContext *ctx);

    antlrcpp::Any visitComputeOperation(NaturalParser::ComputeOperationContext *ctx);

    antlrcpp::Any visitArithmaticOperation(NaturalParser::ArithmaticOperationContext *ctx);

    antlrcpp::Any visitOptionalCompute(NaturalParser::OptionalComputeContext *ctx);

    antlrcpp::Any visitCalculations(NaturalParser::CalculationsContext *ctx);

    antlrcpp::Any visitAddContent(NaturalParser::AddContentContext *ctx);

    antlrcpp::Any visitCompOp(NaturalParser::CompOpContext *ctx);

    antlrcpp::Any visitArithmaticOp(NaturalParser::ArithmaticOpContext *ctx);

    antlrcpp::Any visitEndStatement(NaturalParser::EndStatementContext *ctx);

    antlrcpp::Any visitOtherStatement(NaturalParser::OtherStatementContext *ctx);

};